length = 20.0
outputPath = "./out.txt"

[fermions]
mass = 1.0
nModes = 25
minNumber = 0
maxNumber = 1

[antifermions]
minNumber = 0
maxNumber = 1

[bosons]
mass = 0.5
nModes = 25
minNumber = 0
maxNumber = 2

[write]
ketMap = false
H0 = true
V = true
fermiPosOps = true
antifermiPosOps = true
bosonPosOps = true