length = 20.0
outputPath = "./out.txt"

[fermions]
mass = 1.0
nModes = 5
minNumber = 0
maxNumber = 1

[antifermions]
minNumber = 0
maxNumber = 1

[bosons]
mass = 0.5
nModes = 5
minNumber = 0
maxNumber = 2
